import AppKit
import Foundation

struct ProfileInvocation {
    let profileID: String
    let selectedPaths: [String]

    static func parse(_ arguments: [String]) -> ProfileInvocation? {
        guard
            let marker = arguments.firstIndex(of: "--run-profile"),
            arguments.indices.contains(marker + 1)
        else {
            return nil
        }

        let separator = arguments[(marker + 2)...].firstIndex(of: "--")
        let pathStart = separator.map { $0 + 1 } ?? marker + 2
        let paths = arguments.indices.contains(pathStart)
            ? Array(arguments[pathStart...])
            : []
        return ProfileInvocation(
            profileID: arguments[marker + 1],
            selectedPaths: paths
        )
    }
}

struct ProfileCommandRunner {
    private let fileManager = FileManager.default
    private let scriptManager = TemporaryScriptManager()

    func run(_ invocation: ProfileInvocation, using store: ProfileStore) async throws {
        guard let profile = store.profile(id: invocation.profileID) else {
            throw CommandRunnerError.profileNotFound
        }
        guard !invocation.selectedPaths.isEmpty else {
            throw CommandRunnerError.noSelection
        }

        let scriptURL = scriptManager.scriptURL(for: profile)
        let command = try CommandTemplate.resolve(
            executable: profile.executable,
            arguments: profile.arguments,
            targets: invocation.selectedPaths
        )
            .map(\.shellQuoted)
            .joined(separator: " ")
        let workingDirectory = workingDirectory(for: invocation.selectedPaths)
        let invocationLine = profile.preserveSessionAfterCommand
            ? "\(command)\nexec \"${SHELL:-/bin/zsh}\" -l"
            : "exec \(command)"
        let script = """
        #!/bin/zsh
        # Generated by f2t. Safe to delete.
        cd \(workingDirectory.path.shellQuoted) || exit 1
        \(invocationLine)

        """
        try script.write(to: scriptURL, atomically: true, encoding: .utf8)
        try fileManager.setAttributes(
            [.posixPermissions: 0o700],
            ofItemAtPath: scriptURL.path
        )

        guard let terminalURL = NSWorkspace.shared.urlForApplication(
            withBundleIdentifier: "com.apple.Terminal"
        ) else {
            throw CommandRunnerError.terminalNotFound
        }

        try await withCheckedThrowingContinuation {
            (continuation: CheckedContinuation<Void, Error>) in
            NSWorkspace.shared.open(
                [scriptURL],
                withApplicationAt: terminalURL,
                configuration: NSWorkspace.OpenConfiguration()
            ) { _, error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume()
                }
            }
        }
    }

    private func workingDirectory(for paths: [String]) -> URL {
        let firstURL = URL(fileURLWithPath: paths[0])
        var isDirectory: ObjCBool = false
        if fileManager.fileExists(
            atPath: firstURL.path,
            isDirectory: &isDirectory
        ), isDirectory.boolValue {
            return firstURL
        }
        return firstURL.deletingLastPathComponent()
    }
}

enum CommandRunnerError: LocalizedError {
    case profileNotFound
    case noSelection
    case terminalNotFound

    var errorDescription: String? {
        switch self {
        case .profileNotFound:
            String(localized: "errors.command.profile_not_found")
        case .noSelection:
            String(localized: "errors.command.no_selection")
        case .terminalNotFound:
            String(localized: "errors.command.terminal_not_found")
        }
    }
}
